---
# tasks file for elk-repo

# Add Elasticsearch apt key
- name: Add Elasticsearch apt key
  apt_key:
   url: "https://packages.elastic.co/GPG-KEY-elasticsearch"
   state: present

# Add the Elasticsearch apt repo.
- name: Adding Elasticsearch repo
  apt_repository:
   repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
   state: present